version: '3'
services:
  application:
    container_name: santa
    build: .
    ports:
      - "8080:8080"
    networks:
      - santa
    depends_on:
      - db

  db:
    image: mariadb
    ports:
      - "3306:3306"
    container_name: maria
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: santa
    networks:
      - santa
networks:
  santa: