spring:
  datasource:
    url: jdbc:mysql://localhost:3306/santa
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      data-locations: "classpath*:data.sql"
